# Generated by Django 5.2.6 on 2025-09-14 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(280)], verbose_name='内容')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('replies_count', models.PositiveIntegerField(default=0, verbose_name='回复数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'comment_likes',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='帖子数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话题标签',
                'verbose_name_plural': '话题标签',
                'db_table': 'hashtags',
                'ordering': ['-posts_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='最多280个字符', validators=[django.core.validators.MaxLengthValidator(280)], verbose_name='内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='分享数')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '帖子标签',
                'verbose_name_plural': '帖子标签',
                'db_table': 'post_hashtags',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/', verbose_name='图片')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='替代文本')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'post_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
