# Generated by Django 5.2.6 on 2025-09-14 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('spam', '垃圾信息'), ('harassment', '骚扰'), ('inappropriate', '不当内容'), ('other', '其他')], max_length=200, verbose_name='屏蔽原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='屏蔽时间')),
            ],
            options={
                'verbose_name': '屏蔽关系',
                'verbose_name_plural': '屏蔽关系',
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='会话标题')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '私信会话',
                'verbose_name_plural': '私信会话',
                'db_table': 'conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系',
                'db_table': 'follows',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=20, verbose_name='消息类型')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='附件')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('is_edited', models.BooleanField(default=False, verbose_name='已编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '私信消息',
                'verbose_name_plural': '私信消息',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '消息已读状态',
                'verbose_name_plural': '消息已读状态',
                'db_table': 'message_reads',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('user', '用户'), ('post', '帖子'), ('comment', '评论'), ('message', '私信')], max_length=20, verbose_name='举报类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾信息'), ('harassment', '骚扰'), ('hate_speech', '仇恨言论'), ('violence', '暴力内容'), ('inappropriate', '不当内容'), ('copyright', '版权侵犯'), ('other', '其他')], max_length=50, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('reviewing', '审核中'), ('resolved', '已解决'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态')),
                ('resolution', models.TextField(blank=True, verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
