# Generated by Django 5.2.6 on 2025-09-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_likes', models.BooleanField(default=True, verbose_name='邮件通知-点赞')),
                ('email_comments', models.BooleanField(default=True, verbose_name='邮件通知-评论')),
                ('email_follows', models.BooleanField(default=True, verbose_name='邮件通知-关注')),
                ('email_mentions', models.BooleanField(default=True, verbose_name='邮件通知-提及')),
                ('email_messages', models.BooleanField(default=True, verbose_name='邮件通知-私信')),
                ('email_system', models.BooleanField(default=True, verbose_name='邮件通知-系统')),
                ('push_likes', models.BooleanField(default=True, verbose_name='推送通知-点赞')),
                ('push_comments', models.BooleanField(default=True, verbose_name='推送通知-评论')),
                ('push_follows', models.BooleanField(default=True, verbose_name='推送通知-关注')),
                ('push_mentions', models.BooleanField(default=True, verbose_name='推送通知-提及')),
                ('push_messages', models.BooleanField(default=True, verbose_name='推送通知-私信')),
                ('push_system', models.BooleanField(default=True, verbose_name='推送通知-系统')),
                ('web_likes', models.BooleanField(default=True, verbose_name='站内通知-点赞')),
                ('web_comments', models.BooleanField(default=True, verbose_name='站内通知-评论')),
                ('web_follows', models.BooleanField(default=True, verbose_name='站内通知-关注')),
                ('web_mentions', models.BooleanField(default=True, verbose_name='站内通知-提及')),
                ('web_messages', models.BooleanField(default=True, verbose_name='站内通知-私信')),
                ('web_system', models.BooleanField(default=True, verbose_name='站内通知-系统')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知设置',
                'verbose_name_plural': '通知设置',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('web', '网页'), ('ios', 'iOS'), ('android', 'Android')], max_length=20, verbose_name='设备类型')),
                ('device_token', models.TextField(verbose_name='设备令牌')),
                ('device_id', models.CharField(max_length=200, unique=True, verbose_name='设备ID')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='应用版本')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='系统版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '推送设备',
                'verbose_name_plural': '推送设备',
                'db_table': 'push_devices',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', '点赞'), ('comment', '评论'), ('follow', '关注'), ('mention', '提及'), ('repost', '转发'), ('message', '私信'), ('system', '系统通知')], max_length=50, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
